name: Build & Publish Docker Image
on:
    workflow_dispatch:
    release:
        types: [published, edited]

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - name: Clone the Repo
        uses: actions/checkout@v4

      - name: Print the variable
        run: echo ${{ vars.DOCKERHUB_USERNAME }}

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            yzhangtufts/scgpt
          tags: type=semver,pattern={{version}}
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}